---
apiVersion: extensions/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain_name }}
    secretName: {{ .Values.name }}-secret
  rules:
  - host: {{ .Values.domain_name }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.name }}
          servicePort: 8000
        path: /

